project:
  type: website
  output-dir: _site

website:
  title: "阿斯巴甜4990"
  site-url: "https://aspartame4990.github.io"
  # search: true
  # navbar:
  #   right: []
  comments:
    giscus:
      repo: "aspartame4990/aspartame4990.github.io"
      repo-id: "R_kgDORkpg1w"
      category: "Used for Giscus"
      category-id: "DIC_kwDORkpg184C4MGl"
      mapping: "pathname"
      reactions-enabled: true
      loading: "lazy"
      input-position: "bottom"
      theme: "preferred_color_scheme"
      language: "zh-CN"

format:
  html:
    theme: cosmo
    toc: true
    html-math-method: katex
    css: styles.css

# editor:
#   render-on-save: true