project:
  type: website
  output-dir: docs

website:
  title: "Aspartame 的博客"
  site-url: "https://aspartame4990.github.io"
  navbar:
    right:
      - text: 首页
        href: index.qmd
      - text: 关于
        href: about.qmd
  comments:
    giscus:
      repo: "aspartame4990/aspartame4990.github.io"
      repo-id: "R_kgDORkpg1w"
      category: "Used for Giscus"
      category-id: "DIC_kwDORkpg184C4MGl"
      mapping: "pathname"
      reactions-enabled: true
      loading: "lazy"
      input-position: "bottom"
      theme: "preferred_color_scheme"
      language: "zh-CN"

format:
  html:
    theme: cosmo
    toc: true
    html-math-method: katex
    css: styles.css
