---
title: "01 - 写偏斜与幻读的关系"
date: "2026-03-11"
description: " "
format:
  html:
    toc: true
    toc-depth: 3
    number-sections: false
---

### 1. 为什么需要事务？

简而言之：**为了简化业务程序员的工作**

如果没有数据库事务，业务程序员在编写涉及到数据修改的代码时，必须纯手工去对抗以下三座大山：

##### 痛点一：无处不在的**并发安全**问题
* **Data Race（数据竞争，物理层面的安全）：** 假设你用普通的 `HashMap` 存储用户的账户余额，在多线程环境下读写，内存数据可能会直接崩溃。你不得不换成 `ConcurrentHashMap` 等线程安全的数据结构。
* **Race Condition（竞态条件，逻辑层面的安全）：** 就算物理层面安全了，逻辑漏洞依然存在。比如 **iPhone 17 抢购场景**：库存只剩最后 1 件，用户甲和乙同时点击购买。两人同时查询，发现库存都是 1，然后各自减 1。结果库存变成了 0，却卖出了两部手机。为了防止这种超卖，程序员必须手动加锁，让并发操作在逻辑上表现得像“串行”一样。   
* **死锁：** 手动加锁极易引发互相等待的死锁。

##### 痛点二：复杂的**数据回滚**逻辑
用户购买商品，正常流程是：扣减库存 -> 扣减余额。   
但是，如果库存扣完了，到了第二步发现用户余额不足怎么办？此时必须把之前扣减的库存加回来。业务程序员必须编写海量的补偿代码来把数据“恢复原样”。

##### 痛点三：脆弱的数据**持久化**
即便前面一切顺利，数据全在内存里。怎么保证断电不丢？程序员需要手动把数据刷入磁盘。但内存更改和写入磁盘之间存在时间差，如果在这短短几毫秒内服务器宕机了，数据依然会丢失。


**数据库事务，就是为了解决这些痛点**

##### 对抗痛点一 ##### 
- 对于**Data Race**, 数据库内部使用了并发安全的数据结构保证物理层面的并发安全
- 对于**Race Condition**，数据库通过**隔离性（Isolation）**保证了事务哪怕在并发执行时，其结果也像是一个接一个串行执行的一样。这种看起来像串行的并发也被称为**可串行化(Serializable)**。
- 对于**死锁**, 数据库内置的死锁检测机制会自动打破僵局。

##### 对抗痛点二 ##### 
数据库保证**原子性（Atomicity）**,或者说**Abortability（可中止性）** ，它允许你在发现余额不足时，只需轻松调用一次 `rollback`，库存就会奇迹般地恢复。

##### 对抗痛点三 ##### 
数据库保证**持久性（Durability）**，只要事务返回了`commit`，那么即使机房断电，数据也不会丢失，一定会落入磁盘。

> **个人观点:** **事务 ≈ 普通并发编程 + 可回滚 (Abortability) + 持久性 (Durability)**。

## 2. 如何实现**隔离性**?

既然“看起来像串行执行”是最安全的，那怎么实现呢？

最简单的做法是给整个数据库上锁，真的让事务一个个串行执行。     

但是这样性能太差了，能不能既允许事务并发执行，又让执行结果看起来像是串行呢?  

就像普通并发编程，对数据上读写**锁**! 但是锁(无论是读锁还是写锁)都必须持有至事务结束！否则就会出现:

* **不可重复读（读写冲突）：** 事务 A 读了变量 *x* 后把读锁释放了，事务 B 趁机修改了 *x* 并提交。事务 A 再次读 *x*，发现数据变了，违背了隔离性
* **脏读（写读冲突）：**如果事务A修改变量x，随后事务B读取变量x、修改x的值之后`commit`，但是随后事务A出现错误需要回滚，但这就导致已经`commit`的事务B也必须回滚，违背了事务的`持久性`
* **丢失更新（写写冲突）：** 同样是用户甲和用户乙抢最后一台iPhone17的例子，如果串行执行的话只能卖出1台，但实际上卖出了2台，结果与串行执行不同，违背了`隔离性`。 

这种持有锁(无论是读锁还是写锁)直至事务结束的并发控制算法也被称为**强严格两阶段锁(Strong Strict 2 Phase Lock)**。    

> **个人观点:** 我们在普通并发编程中，也无意中使用了强严格两阶段锁，即持有读/写锁，直至某个操作结束。

## 3. 聚合操作怎么加锁?

前面的例子中，我们总是读写单个独立的 record，因此给单条 record 加锁就够了。   
但是，在实际业务中，我们有时会读写一个集合。那么问题来了，为了保证`Serializable`，我们需要给集合中的每一条 record 加锁吗?  

假设我们读取集合时，没有给任何record加锁，仅仅在写入集合时给被写入的record加锁，那么就会出现`写倾斜(write skew)`, 请看下面的例子:

- 例1 - 写倾斜: 医院要求至少有 1 名医生在值班。小明和小红目前都在值班，但两人都想请假。
  - 小明（事务A）查询：`SELECT count(*) FROM 医生表 WHERE 值班 = true`，结果为 2。
  - 小红（事务B）同时查询，结果也是 2。
  - 小明觉得还有小红顶着，于是执行 `UPDATE 医生表 SET 值班 = false WHERE 名字 = '小明'`，成功请假。
  - 小红觉得还有小明顶着，执行同样的操作请假成功。
  - 最终值班医生变成了 0 人，业务规则被踩得粉碎。

这是因为没有锁住 `{医生 | 医生.值班 = true}` 这个集合，导致事务各自修改了不同的行，偷偷改变了集合的整体状态。   
因此，为了保证`Serializable`，我们必须锁住集合中的每一条 record，防止集合中的 record 被**修改**或**删除**。   

但是，仅仅保证集合中的record不被修改或删除还不够, 请看下面的例子:

- 例2 - 幻读: 系统要求昵称必须全局唯一。
  - 目前系统里没有叫“张三”的人。
  - 用户甲和乙同时想注册“张三”。两人的事务同时执行：`SELECT count(*) FROM users WHERE username = '张三'`。结果都是 0。
  - 两人都认为可以注册，纷纷执行 `INSERT` 语句。
  - 悲剧发生，系统里出现了两个“张三”。

尽管我们保证了集合`{用户 | 用户.username = '张三'}`不会修改或删除record，但却没有保证集合中不会**新增**record。

通过上面两个例子，我们得出结论，当我们读写一个集合时，要锁住集合来保证集合中的record不会修改、不会新增、不会减少。这种锁被称为**谓词锁**。


## 4. MySQL实现“谓词锁”了吗？

“谓词锁”在理论上无懈可击，但在工程上难以实现。

因此MySQL没有实现谓词锁，而是实现了近似于谓词锁的**索引锁**，索引锁会锁定一个更大的集合。   

索引锁包括2种:

* **间隙锁 (Gap Locks)：** 专门用来锁定索引之间的“开区间”，因此可以用来锁定空集。在注册“张三”的例子中，即便张三还不存在，MySQL 会找到如果张三存在，他应该呆在索引树的哪个位置（比如在“李四”和“王五”之间），然后给这个区间加一把间隙锁。任何试图在这个区间插入“张三”的事务都会被死死卡住。
* **Next-Key Locks：** 约等于 间隙锁 + 行锁，用于锁定左开右闭区间。

**⚠️**但是，无论是间隙锁还是Next-Key Locks，都要求索引必须存在；如果索引不存在，MySQL会锁住整张表。


## 5.总结
幻读与写倾斜的成因相同，都是因为一个事务读写一个集合时，另一个事务修改了这个集合。     
解决方案也相同，用谓词锁(MySQL里的索引锁或者表锁)锁住这个集合。    


> 欢迎感兴趣的朋友留言讨论!